name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *"   # 1x por dia (00:00 UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: Matheus-Machaado
          BRANCH_NAME: "main"
          UTC_OFFSET: -3
